#baseURL = 'https://example.org/'
#languageCode = 'en-us'
#title = 'Shinpu site'
#theme = 'hugo-bearblog'


# Base URL used when generating links to your pages
# Set to the URL for your site
baseURL = "https://example.com"

# Name of the theme
theme = 'hugo-bearblog'

# Basic metadata configuration for your blog.
title = "shinpu.xyz website"
author = "shinpu"
copyright = "GNU GPL"
languageCode = "en-US"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# Generate "blog"-like URL.
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[params]
  # The "description" of your website. This is used in the meta data of your generated html.
  description = "Shinpuxyz website, linux blogging, "

  # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
  # Hint: It's good practise to also put a "favicon.ico"-file into your "static"-folder.
  favicon = "images/favicon.png"

  # These "images" are used for the structured data templates. This will show up, when
  # services like Twitter or Slack want to generate a preview of a link to your site.
  # See https://gohugo.io/templates/internal#twitter-cards and
  # https://gohugo.io/templates/internal#open-graph.
  images = ["images/share.png"]

  # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
  title = "shinpu.xyz"

  # hideMadeWithLine = true

